# Generated by Django 5.1.2 on 2025-11-19 05:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import unifiedapiapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CdacProject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CdVerifierAndNonce",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("stateId", models.CharField(max_length=255)),
                ("code_verifier", models.TextField()),
                ("nonce", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("employee_id", models.CharField(max_length=10, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("group", models.CharField(max_length=50)),
                ("fla_name", models.CharField(max_length=100)),
                ("fla_employee_id", models.CharField(max_length=10)),
                ("fla_email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "confirm_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("file_path", models.CharField(max_length=500)),
                ("image_id", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Metric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Registration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "organization",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                ("password", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "confirm_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vdi_required", models.BooleanField(default=False)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("flavor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "login_enable_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "login_disable_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "login_enable_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "login_disable_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("storage_required", models.BooleanField(default=False)),
                (
                    "additional_storage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=100)),
                ("service_name", models.CharField(max_length=255)),
                ("purpose", models.TextField(blank=True, null=True)),
                ("project_name", models.CharField(max_length=255)),
                ("designation", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("purpose_of_request", models.TextField(blank=True, null=True)),
                (
                    "admin_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "fla_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "request_timestamp",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("fla_approved_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_approved_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("service_start_date", models.DateField(blank=True, null=True)),
                ("service_end_date", models.DateField(blank=True, null=True)),
                ("service_requirements", models.TextField(blank=True, null=True)),
                ("additional_notes", models.TextField(blank=True, null=True)),
                ("fla_rejection_reason", models.TextField(blank=True, null=True)),
                ("admin_rejection_reason", models.TextField(blank=True, null=True)),
                ("fla_action_timestamp", models.DateTimeField(blank=True, null=True)),
                ("admin_action_timestamp", models.DateTimeField(blank=True, null=True)),
                ("app_name", models.CharField(blank=True, max_length=100, null=True)),
                ("replica", models.IntegerField(blank=True, null=True)),
                (
                    "root_password",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("username", models.CharField(blank=True, max_length=100, null=True)),
                ("password", models.CharField(blank=True, max_length=100, null=True)),
                ("database", models.CharField(blank=True, max_length=100, null=True)),
                ("node_port", models.IntegerField(blank=True, null=True)),
                (
                    "deployment_status",
                    models.CharField(default="Not Deployed", max_length=20),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserRegistrationRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("employee_id", models.CharField(max_length=50)),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("Employee", "Employee"), ("FLA", "FLA")],
                        max_length=20,
                    ),
                ),
                (
                    "fla_employee_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "fla_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "admin_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Accepted", "Accepted"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=20,
                    ),
                ),
                (
                    "temporary_password",
                    models.CharField(blank=True, max_length=128, null=True),
                ),
                ("request_timestamp", models.DateTimeField(auto_now_add=True)),
                ("fla_approved_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_approved_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("fla_rejection_reason", models.TextField(blank=True, null=True)),
                ("admin_rejection_reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VMInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vm_name", models.CharField(blank=True, max_length=255, null=True)),
                ("vm_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "shutoff_status",
                    models.BooleanField(blank=True, default=False, null=True),
                ),
                ("host_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "instance_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vnc_display", models.IntegerField(blank=True, null=True)),
                ("username", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ip",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                (
                    "vm_access_from_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vm_access_to_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vm_access_from_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vm_access_to_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "requested_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "creation_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("volume_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "data_volume_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("zabbix_hostid", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="VmRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("employee_id", models.CharField(max_length=10)),
                ("count_of_vms", models.IntegerField(blank=True, null=True)),
                (
                    "vm_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                ("purpose", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vdi_required", models.BooleanField(default=False)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                ("flavor", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "login_enable_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "login_disable_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "login_enable_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "login_disable_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("storage_required", models.BooleanField(default=False)),
                (
                    "additional_storage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "admin_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fla_status", models.CharField(blank=True, max_length=255, null=True)),
                ("purpose_of_request", models.TextField(blank=True, null=True)),
                ("request_timestamp", models.DateTimeField(blank=True, null=True)),
                ("fla_approved_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_approved_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("creation_status", models.TextField(blank=True, null=True)),
                ("fla_rejection_reason", models.TextField(blank=True, null=True)),
                ("admin_rejection_reason", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("issue", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=unifiedapiapp.models.ticket_attachment_upload_path,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("solution", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Closed", "Closed"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("status_updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to="unifiedapiapp.employee",
                    ),
                ),
            ],
        ),
    ]
