# Generated by Django 5.1.2 on 2025-12-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedapiapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmrequest',
            name='creation_error_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
