# Generated by Django 5.1.2 on 2025-12-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unifiedapiapp", "0002_vmrequest_creation_error_message"),
    ]

    operations = [
        migrations.AddField(
            model_name="vmrequest",
            name="delete_request_status",
            field=models.CharField(default="None", max_length=20),
        ),
    ]
