# Generated by Django 5.1.2 on 2025-12-08 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unifiedapiapp", "0003_vmrequest_delete_request_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vmrequest",
            name="delete_request_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
