# Generated by Django 5.1.2 on 2025-12-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unifiedapiapp", "0004_vmrequest_delete_request_reason"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletedVMLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("employee_id", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "designation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "requested_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("vm_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "vm_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=255, null=True
                    ),
                ),
                (
                    "instance_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("host_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "ip",
                    models.CharField(blank=True, default="", max_length=255, null=True),
                ),
                ("vnc_display", models.IntegerField(blank=True, null=True)),
                ("shutoff_status", models.BooleanField(default=False)),
                ("volume_id", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "data_volume_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("storage_required", models.BooleanField(default=False)),
                (
                    "additional_storage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("flavor", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("purpose", models.CharField(blank=True, max_length=255, null=True)),
                ("purpose_of_request", models.TextField(blank=True, null=True)),
                (
                    "admin_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fla_status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "creation_status",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("fla_rejection_reason", models.TextField(blank=True, null=True)),
                ("admin_rejection_reason", models.TextField(blank=True, null=True)),
                ("creation_error_message", models.TextField(blank=True, null=True)),
                (
                    "vm_access_from_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vm_access_to_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vm_access_from_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "vm_access_to_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "login_enable_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "login_disable_date",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "login_enable_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "login_disable_time",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("request_timestamp", models.DateTimeField(blank=True, null=True)),
                ("fla_approved_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_approved_timestamp",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "delete_request_status",
                    models.CharField(default="None", max_length=20),
                ),
                ("delete_request_reason", models.TextField(blank=True, null=True)),
                (
                    "delete_approved_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("delete_approved_at", models.DateTimeField(auto_now_add=True)),
                ("remarks", models.CharField(blank=True, max_length=255, null=True)),
                ("count_of_vms", models.IntegerField(blank=True, null=True)),
                ("zabbix_hostid", models.IntegerField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
