# Generated by Django 5.1.2 on 2025-12-09 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unifiedapiapp", "0005_deletedvmlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="vminfo",
            name="connection_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
