# Generated by Django 5.1.2 on 2025-12-15 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unifiedapiapp", "0006_vminfo_connection_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="vmrequest",
            name="admin_action_timestamp",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
