# Generated by Django 5.1.2 on 2025-12-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedapiapp', '0007_vmrequest_admin_action_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminfo',
            name='created_via_cmp',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vminfo',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
