# Generated by Django 5.1.2 on 2025-12-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedapiapp', '0008_vminfo_created_via_cmp_vminfo_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vminfo',
            name='created_via_cmp',
        ),
        migrations.RemoveField(
            model_name='vminfo',
            name='deleted_at',
        ),
    ]
