# Generated by Django 5.1.2 on 2025-12-24 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("unifiedapiapp", "0009_remove_vminfo_created_via_cmp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="confirm_password",
        ),
        migrations.RemoveField(
            model_name="employee",
            name="password",
        ),
    ]
