# Generated by Django 5.1.2 on 2025-12-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unifiedapiapp", "0010_remove_employee_confirm_password_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="designation",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
