# Generated by Django 5.1.2 on 2025-12-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("unifiedapiapp", "0012_employee_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="vmrequest",
            name="network_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vmrequest",
            name="network_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
