# Generated by Django 5.1.2 on 2025-12-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedapiapp', '0013_vmrequest_network_id_vmrequest_network_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_fla',
            field=models.BooleanField(default=False),
        ),
    ]
