# Generated by Django 5.1.2 on 2026-01-12 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedapiapp', '0014_employee_is_fla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='fla_employee_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fla_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
