# Generated by Django 5.1.2 on 2026-02-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedapiapp', '0015_alter_employee_fla_employee_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vminfo',
            name='vm_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
