# Generated by Django 5.1.2 on 2026-02-12 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedapiapp', '0016_alter_vminfo_vm_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='delete_request_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='delete_request_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20, null=True),
        ),
    ]
