# Generated by Django 5.1.2 on 2026-02-13 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedapiapp', '0017_servicerequest_delete_request_reason_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vminfo',
            name='data_volume_id',
        ),
        migrations.RemoveField(
            model_name='vminfo',
            name='zabbix_hostid',
        ),
        migrations.RemoveField(
            model_name='vmrequest',
            name='delete_request_reason',
        ),
        migrations.RemoveField(
            model_name='vmrequest',
            name='delete_request_status',
        ),
        migrations.AddField(
            model_name='vminfo',
            name='delete_request_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vminfo',
            name='delete_request_status',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
