# Generated by Django 5.1.2 on 2026-02-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unifiedapiapp', '0018_remove_vminfo_data_volume_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vminfo',
            name='data_volume_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
